name: gemini_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  delayed_display: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - public/assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: public/assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
          
    - family: Montserrat
      fonts:
        - asset: public/assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: public/assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: public/assets/fonts/Montserrat/static/Montserrat-Semibold.ttf
          weight: 600
        - asset: public/assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: public/assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800